name: AI Issue Processing

on:
  issues:
    types: [labeled]
  workflow_dispatch:

jobs:
  issue-processing:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      models: read
      issues: write
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Call GitHub Model API
        id: ai-inference
        uses: actions/ai-inference@v1
        with:
          model: gpt-4o-mini
          prompt: |
            'Hello!'

      - name: Parse and Apply Labels
        env:
          AI_RESPONSE: ${{ steps.ai-inference.outputs.response }}
        run: |
          echo "${{ steps.ai-inference.outputs.response }}
