on:
  issue_comment:
    types: [created]

jobs:
  echo-chamber:
    if: ${{ startsWith('aaa','b') || true || startsWith('aaa', '/bench ') }}
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo 'AAAAAAAAAAA'
