name: Hello World Workflow

on: 
  pull_request:  # Trigger the workflow on pull request events

jobs:
  say-hello:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner
    steps:
      - name: Echo Hello
        run: env
