# This workflow checks if an ADO ID (AB#ID) has been set successfully (https://github.com/marketplace/actions/azure-boards-check-for-ab)
# If so, the workflow will extract the AB ID from the message
# then it will update the PR title adding ',Fixed AB#ID' at the end.
# Why?
# Adding ',Fixed AB#ID' to the PR title will make the PR to automatically resolve the associated ADO item when the PR is completed.

name: 'AB#ID Check'
on: 
  pull_request:
    types: [opened, reopened, edited, labeled, synchronize]

jobs:
  check-and-apply-abid:
    name: Check and apply AB#ID to PR title
    permissions:
      contents: read
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    if: "!contains(github.event.pull_request.labels.*.name, 'skip AB ID validation')"
    steps:
      - name: Validate PR is linked to a work item
        uses: danhellem/github-actions-pr-is-linked-to-work-item@main
        continue-on-error: true

      - name: Prepare environment
        id: env
        run: |
          echo "pr_number=${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT
          echo "pr_body<<EOF" >> $GITHUB_OUTPUT
          echo "${{ github.event.pull_request.body }}" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
